# Generated by Django 5.2.8 on 2025-11-21 14:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_destination_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
