# Generated by Django 5.2.8 on 2025-11-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='images/')),
                ('desc', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
